draw_text(900, 500, fps)
if (obj_player1.spotlight == 1)
    pal_swap_set(obj_player1.spr_palette, obj_player1.paletteselect, 0)
else
    pal_swap_set(obj_player2.spr_palette, obj_player2.paletteselect, 0)
if (obj_player.backupweapon == 1)
    draw_sprite_ext(spr_shotgunbackup, -1, 50, 100, 1, 1, 1, c_white, alpha)
if (obj_player.state != states.gameover)
{
    if (obj_player1.character == "P" && obj_player1.spotlight == 1)
    {
        if (shoving == 1)
        {
            if (image_index < 3)
                draw_sprite_ext(spr_noiseHUD_idle, image_index, 125, 100, 1, 1, 1, c_white, alpha)
            draw_sprite_ext(spr_pepinoHUD_shove, image_index, 125, 100, 1, 1, 1, c_white, alpha)
        }
        else if (obj_player1.sprite_index == spr_knightpep_thunder)
            draw_sprite_ext(spr_pepinoHUDthunder, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index != spr_knightpep_start && (obj_player1.state == states.knightpep || obj_player1.state == states.knightpepslopes))
            draw_sprite_ext(spr_pepinoHUDknight, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == spr_bombpep_end)
            draw_sprite_ext(spr_pepinoHUDbombend, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (instance_exists(obj_itspizzatime) || obj_player1.sprite_index == spr_bombpep_intro || obj_player1.sprite_index == spr_bombpep_runabouttoexplode || obj_player1.sprite_index == spr_bombpep_run || obj_player1.sprite_index == spr_player_fireass)
            draw_sprite_ext(spr_pepinoHUDscream, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.Sjumpland || (obj_player1.state == states.freefallland && shake_mag > 0))
            draw_sprite_ext(spr_pepinoHUDstun, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == spr_player_victory || obj_player1.state == states.keyget || obj_player1.state == states.smirk || obj_player1.state == states.gottreasure || (obj_player1.state == states.bossintro && obj_player1.sprite_index == spr_player_levelcomplete))
            draw_sprite_ext(spr_pepinoHUDhappy, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == spr_player_machroll || obj_player1.sprite_index == spr_player_tumble)
            draw_sprite_ext(spr_pepinoHUDrolling, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.combo >= 3)
            draw_sprite_ext(spr_pepinoHUDmenacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.mach1 || obj_player1.state == states.chainsaw || obj_player1.state == states.freefallprep || obj_player1.state == states.freefall || obj_player1.state == states.tackle || obj_player1.state == states.Sjump || obj_player1.state == states.slam || obj_player1.state == states.Sjumpprep || obj_player1.state == states.grab || obj_player1.state == states.punch || obj_player1.state == states.backbreaker || obj_player1.state == states.backkick || obj_player1.state == states.uppunch || obj_player1.state == states.shoulder)
            draw_sprite_ext(spr_pepinoHUDmach1, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.mach2 || obj_player1.sprite_index == spr_player_dive || obj_player1.sprite_index == spr_player_machslideboost || obj_player1.state == states.climbwall || obj_player1.state == states.handstandjump || obj_player1.state == states.superslam)
            draw_sprite_ext(spr_pepinoHUDmach2, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.mach3 && obj_player1.sprite_index == spr_player_crazyrun)
            draw_sprite_ext(spr_pepinoHUDmach4, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.mach3 || obj_player1.sprite_index == spr_player_machslideboost3)
            draw_sprite_ext(spr_pepinoHUDmach3, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.hurt || obj_player1.sprite_index == spr_bombpep_end || obj_player1.sprite_index == spr_player_fireassend || obj_player1.state == states.timesup || obj_player1.state == states.bombpep || (obj_player1.state == states.bossintro && obj_player1.sprite_index == spr_player_bossintro) || (obj_player1.state == states.bossintro && obj_player1.sprite_index == spr_player_idle))
            draw_sprite_ext(spr_pepinoHUDhurt, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.angry == 1)
            draw_sprite_ext(spr_pepinoHUD3hp, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == spr_player_hurtidle || obj_player1.sprite_index == spr_player_hurtwalk)
            draw_sprite_ext(spr_pepinoHUD1hp, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.panic == 1 || global.snickchallenge == 1 || global.miniboss == 1)
            draw_sprite_ext(spr_pepinoHUDpanic, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == spr_shotgun_pullout)
            draw_sprite_ext(spr_pepinoHUDmenacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else
            draw_sprite_ext(spr_pepinoHUD, -1, 125, 100, 1, 1, 1, c_white, alpha)
    }
    if (obj_player2.character == "P" && obj_player1.spotlight == 0)
    {
        if (shoving == 1)
        {
            if (image_index < 3)
                draw_sprite_ext(spr_noiseHUD_idle, image_index, 125, 100, 1, 1, 1, c_white, alpha)
            draw_sprite_ext(spr_pepinoHUD_shove, image_index, 125, 100, 1, 1, 1, c_white, alpha)
        }
        else if (obj_player2.sprite_index == spr_knightpep_thunder)
            draw_sprite_ext(spr_pepinoHUDthunder, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index != spr_knightpep_start && (obj_player2.state == states.knightpep || obj_player2.state == states.knightpepslopes))
            draw_sprite_ext(spr_pepinoHUDknight, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == spr_bombpep_end)
            draw_sprite_ext(spr_pepinoHUDbombend, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (instance_exists(obj_itspizzatime) || obj_player2.sprite_index == spr_bombpep_intro || obj_player2.sprite_index == spr_bombpep_runabouttoexplode || obj_player2.sprite_index == spr_bombpep_run || obj_player2.sprite_index == spr_player_fireass)
            draw_sprite_ext(spr_pepinoHUDscream, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.Sjumpland || (obj_player2.state == states.freefallland && shake_mag > 0))
            draw_sprite_ext(spr_pepinoHUDstun, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == spr_player_victory || obj_player2.state == states.keyget || obj_player2.state == states.smirk || obj_player2.state == states.gottreasure || (obj_player2.state == states.bossintro && obj_player2.sprite_index == spr_player_levelcomplete))
            draw_sprite_ext(spr_pepinoHUDhappy, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == spr_player_machroll || obj_player2.sprite_index == spr_player_tumble)
            draw_sprite_ext(spr_pepinoHUDrolling, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.combo >= 3)
            draw_sprite_ext(spr_pepinoHUDmenacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.mach1 || obj_player2.state == states.chainsaw || obj_player2.state == states.freefallprep || obj_player2.state == states.freefall || obj_player2.state == states.tackle || obj_player2.state == states.Sjump || obj_player2.state == states.slam || obj_player2.state == states.Sjumpprep || obj_player2.state == states.grab || obj_player2.state == states.punch || obj_player2.state == states.backbreaker || obj_player2.state == states.backkick || obj_player2.state == states.uppunch || obj_player2.state == states.shoulder)
            draw_sprite_ext(spr_pepinoHUDmach1, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.mach2 || obj_player2.sprite_index == spr_player_dive || obj_player2.sprite_index == spr_player_machslideboost || obj_player2.state == states.climbwall || obj_player2.state == states.handstandjump || obj_player2.state == states.superslam)
            draw_sprite_ext(spr_pepinoHUDmach2, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.mach3 && obj_player2.sprite_index == spr_player_crazyrun)
            draw_sprite_ext(spr_pepinoHUDmach4, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.mach3 || obj_player2.sprite_index == spr_player_machslideboost3)
            draw_sprite_ext(spr_pepinoHUDmach3, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.hurt || obj_player2.sprite_index == spr_bombpep_end || obj_player2.sprite_index == spr_player_fireassend || obj_player2.state == states.timesup || obj_player2.state == states.bombpep || (obj_player2.state == states.bossintro && obj_player2.sprite_index == spr_player_bossintro) || (obj_player2.state == states.bossintro && obj_player2.sprite_index == spr_player_idle))
            draw_sprite_ext(spr_pepinoHUDhurt, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.angry == 1)
            draw_sprite_ext(spr_pepinoHUD3hp, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == spr_player_hurtidle || obj_player2.sprite_index == spr_player_hurtwalk)
            draw_sprite_ext(spr_pepinoHUD1hp, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.panic == 1 || global.snickchallenge == 1 || global.miniboss == 1)
            draw_sprite_ext(spr_pepinoHUDpanic, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == spr_shotgun_pullout)
            draw_sprite_ext(spr_pepinoHUDmenacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else
            draw_sprite_ext(spr_pepinoHUD, -1, 125, 100, 1, 1, 1, c_white, alpha)
    }
    if (obj_player.character == "S")
        draw_sprite_ext(spr_snickHUD, -1, 125, 60, 1, 1, 1, c_white, alpha)
    if (obj_player2.character == "N" && obj_player1.spotlight == 0)
    {
        if (shoving == 1)
        {
            if (image_index < 3)
                draw_sprite_ext(spr_pepinoHUD, image_index, 125, 100, 1, 1, 1, c_white, alpha)
            draw_sprite_ext(spr_noiseHUD_shove, image_index, 125, 100, 1, 1, 1, c_white, alpha)
        }
        else if (obj_player2.sprite_index == obj_player2.spr_knightpepthunder)
            draw_sprite_ext(spr_noiseHUD_thunder, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index != obj_player2.spr_knightpepstart && (obj_player2.state == states.knightpep || obj_player2.state == states.knightpepslopes))
            draw_sprite_ext(spr_noiseHUD_knight, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == obj_player2.spr_bombpepend)
            draw_sprite_ext(spr_noiseHUD_bomb, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (instance_exists(obj_itspizzatime) || obj_player2.sprite_index == obj_player2.spr_bombpepintro || obj_player2.sprite_index == obj_player2.spr_bombpeprunabouttoexplode || obj_player2.sprite_index == obj_player2.spr_bombpeprun || obj_player2.sprite_index == obj_player2.spr_fireass)
            draw_sprite_ext(spr_noiseHUD_panic, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.Sjumpland || (obj_player2.state == states.freefallland && shake_mag > 0))
            draw_sprite_ext(spr_noiseHUD_groundpound, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == obj_player2.spr_victory || obj_player2.state == states.keyget || obj_player2.state == states.smirk || obj_player2.state == states.gottreasure || (obj_player2.state == states.bossintro && obj_player2.sprite_index == obj_player2.spr_player_levelcomplete))
            draw_sprite_ext(spr_noiseHUD_happy, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.combo >= 3)
            draw_sprite_ext(spr_noiseHUD_menacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.mach1 || obj_player2.state == states.chainsaw || obj_player2.state == states.freefallprep || obj_player2.state == states.freefall || obj_player2.state == states.tackle || obj_player2.state == states.Sjump || obj_player2.state == states.slam || obj_player2.state == states.Sjumpprep || obj_player2.state == states.grab || obj_player2.state == states.punch || obj_player2.state == states.backbreaker || obj_player2.state == states.backkick || obj_player2.state == states.uppunch || obj_player2.state == states.shoulder)
            draw_sprite_ext(spr_noiseHUD_mach1, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.pogo || obj_player2.state == states.mach2 || obj_player2.sprite_index == obj_player2.spr_dive || obj_player2.sprite_index == obj_player2.spr_machslideboost || obj_player2.state == states.climbwall || obj_player2.state == states.handstandjump || obj_player2.state == states.superslam)
            draw_sprite_ext(spr_noiseHUD_mach2, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.mach3 && obj_player2.sprite_index == obj_player2.spr_crazyrun)
            draw_sprite_ext(spr_noiseHUD_crazyrun, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.mach3 || obj_player2.sprite_index == obj_player2.spr_mach3boost)
            draw_sprite_ext(spr_noiseHUD_mach3, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.state == states.hurt || obj_player2.sprite_index == obj_player2.spr_bombpepend || obj_player2.sprite_index == obj_player2.spr_fireassend || obj_player2.state == states.timesup || obj_player2.state == states.bombpep || (obj_player2.state == states.bossintro && obj_player2.sprite_index == obj_player2.spr_player_bossintro) || (obj_player2.state == states.bossintro && obj_player2.sprite_index == obj_player2.spr_idle))
            draw_sprite_ext(spr_noiseHUD_hurt, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.angry == 1)
            draw_sprite_ext(spr_noiseHUD_angry, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == obj_player2.spr_hurtidle || obj_player2.sprite_index == obj_player2.spr_hurtwalk)
            draw_sprite_ext(spr_noiseHUD_lowhealth, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.panic == 1 || global.snickchallenge == 1 || global.miniboss == 1)
            draw_sprite_ext(spr_noiseHUD_panic, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player2.sprite_index == spr_shotgun_pullout)
            draw_sprite_ext(spr_noiseHUD_menacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else
            draw_sprite_ext(spr_noiseHUD_idle, -1, 125, 100, 1, 1, 1, c_white, alpha)
    }
    if (obj_player1.character == "N" && obj_player1.spotlight == 1)
    {
        if (shoving == 1)
        {
            if (image_index < 3)
                draw_sprite_ext(spr_pepinoHUD, image_index, 125, 100, 1, 1, 1, c_white, alpha)
            draw_sprite_ext(spr_noiseHUD_shove, image_index, 125, 100, 1, 1, 1, c_white, alpha)
        }
        else if (obj_player1.sprite_index == obj_player1.spr_knightpepthunder)
            draw_sprite_ext(spr_noiseHUD_thunder, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index != obj_player1.spr_knightpepstart && (obj_player1.state == states.knightpep || obj_player1.state == states.knightpepslopes))
            draw_sprite_ext(spr_noiseHUD_knight, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == obj_player1.spr_bombpepend)
            draw_sprite_ext(spr_noiseHUD_bomb, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (instance_exists(obj_itspizzatime) || obj_player1.sprite_index == obj_player1.spr_bombpepintro || obj_player1.sprite_index == obj_player1.spr_bombpeprunabouttoexplode || obj_player1.sprite_index == obj_player1.spr_bombpeprun || obj_player1.sprite_index == obj_player1.spr_fireass)
            draw_sprite_ext(spr_noiseHUD_panic, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.Sjumpland || (obj_player1.state == states.freefallland && shake_mag > 0))
            draw_sprite_ext(spr_noiseHUD_groundpound, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == obj_player1.spr_victory || obj_player1.state == states.keyget || obj_player1.state == states.smirk || obj_player1.state == states.gottreasure || (obj_player1.state == states.bossintro && obj_player1.sprite_index == obj_player1.spr_player_levelcomplete))
            draw_sprite_ext(spr_noiseHUD_happy, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.combo >= 3)
            draw_sprite_ext(spr_noiseHUD_menacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.mach1 || obj_player1.state == states.chainsaw || obj_player1.state == states.freefallprep || obj_player1.state == states.freefall || obj_player1.state == states.tackle || obj_player1.state == states.Sjump || obj_player1.state == states.slam || obj_player1.state == states.Sjumpprep || obj_player1.state == states.grab || obj_player1.state == states.punch || obj_player1.state == states.backbreaker || obj_player1.state == states.backkick || obj_player1.state == states.uppunch || obj_player1.state == states.shoulder)
            draw_sprite_ext(spr_noiseHUD_mach1, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.pogo || obj_player1.state == states.mach2 || obj_player1.sprite_index == obj_player1.spr_dive || obj_player1.sprite_index == obj_player1.spr_machslideboost || obj_player1.state == states.climbwall || obj_player1.state == states.handstandjump || obj_player1.state == states.superslam)
            draw_sprite_ext(spr_noiseHUD_mach2, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.mach3 && obj_player1.sprite_index == obj_player1.spr_crazyrun)
            draw_sprite_ext(spr_noiseHUD_crazyrun, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.mach3 || obj_player1.sprite_index == obj_player1.spr_mach3boost)
            draw_sprite_ext(spr_noiseHUD_mach3, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.state == states.hurt || obj_player1.sprite_index == obj_player1.spr_bombpepend || obj_player1.sprite_index == obj_player1.spr_fireassend || obj_player1.state == states.timesup || obj_player1.state == states.bombpep || (obj_player1.state == states.bossintro && obj_player1.sprite_index == obj_player1.spr_player_bossintro) || (obj_player1.state == states.bossintro && obj_player1.sprite_index == obj_player1.spr_idle))
            draw_sprite_ext(spr_noiseHUD_hurt, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.angry == 1)
            draw_sprite_ext(spr_noiseHUD_angry, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == obj_player1.spr_hurtidle || obj_player1.sprite_index == obj_player1.spr_hurtwalk)
            draw_sprite_ext(spr_noiseHUD_lowhealth, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (global.panic == 1 || global.snickchallenge == 1 || global.miniboss == 1)
            draw_sprite_ext(spr_noiseHUD_panic, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else if (obj_player1.sprite_index == spr_shotgun_pullout)
            draw_sprite_ext(spr_noiseHUD_menacing, -1, 125, 100, 1, 1, 1, c_white, alpha)
        else
            draw_sprite_ext(spr_noiseHUD_idle, -1, 125, 100, 1, 1, 1, c_white, alpha)
    }
    shader_reset()
    if (obj_player1.spotlight == 1 && obj_player1.character == "P")
    {
        if (obj_player1.movespeed < 2.4 || (!((obj_player1.state == states.mach1 || obj_player1.state == states.mach2 || obj_player1.state == states.mach3 || obj_player1.state == states.climbwall || obj_player1.state == states.machslide || obj_player1.state == states.machroll || obj_player1.state == states.handstandjump))))
            draw_sprite_ext(spr_speedbar, 0, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player1.movespeed >= 2.4 && obj_player1.movespeed < 4.8 && (obj_player1.state == states.mach1 || obj_player1.state == states.mach2 || obj_player1.state == states.mach3 || obj_player1.state == states.climbwall || obj_player1.state == states.machslide || obj_player1.state == states.machroll || obj_player1.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 1, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player1.movespeed >= 4.8 && obj_player1.movespeed < 7.2 && (obj_player1.state == states.mach1 || obj_player1.state == states.mach2 || obj_player1.state == states.mach3 || obj_player1.state == states.climbwall || obj_player1.state == states.machslide || obj_player1.state == states.machroll || obj_player1.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 2, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player1.movespeed >= 7.2 && obj_player1.movespeed < 9.6 && (obj_player1.state == states.mach1 || obj_player1.state == states.mach2 || obj_player1.state == states.mach3 || obj_player1.state == states.climbwall || obj_player1.state == states.machslide || obj_player1.state == states.machroll || obj_player1.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 3, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player1.movespeed >= 9.6 && obj_player1.movespeed < 12 && (obj_player1.state == states.mach1 || obj_player1.state == states.mach2 || obj_player1.state == states.mach3 || obj_player1.state == states.climbwall || obj_player1.state == states.machslide || obj_player1.state == states.machroll || obj_player1.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 4, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player1.movespeed >= 12 && (obj_player1.state == states.mach1 || obj_player1.state == states.mach2 || obj_player1.state == states.mach3 || obj_player1.state == states.climbwall || obj_player1.state == states.machslide || obj_player1.state == states.machroll || obj_player1.state == states.handstandjump))
            draw_sprite_ext(spr_speedbarmax, -1, 125, 140, 1, 1, 1, c_white, alpha)
    }
    else if (obj_player1.spotlight == 0 && obj_player2.character == "P")
    {
        if (obj_player2.movespeed < 2.4 || (!((obj_player2.state == states.mach1 || obj_player2.state == states.mach2 || obj_player2.state == states.mach3 || obj_player2.state == states.climbwall || obj_player2.state == states.machslide || obj_player2.state == states.machroll || obj_player2.state == states.handstandjump))))
            draw_sprite_ext(spr_speedbar, 0, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player2.movespeed >= 2.4 && obj_player2.movespeed < 4.8 && (obj_player2.state == states.mach1 || obj_player2.state == states.mach2 || obj_player2.state == states.mach3 || obj_player2.state == states.climbwall || obj_player2.state == states.machslide || obj_player2.state == states.machroll || obj_player2.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 1, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player2.movespeed >= 4.8 && obj_player2.movespeed < 7.2 && (obj_player2.state == states.mach1 || obj_player2.state == states.mach2 || obj_player2.state == states.mach3 || obj_player2.state == states.climbwall || obj_player2.state == states.machslide || obj_player2.state == states.machroll || obj_player2.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 2, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player2.movespeed >= 7.2 && obj_player2.movespeed < 9.6 && (obj_player2.state == states.mach1 || obj_player2.state == states.mach2 || obj_player2.state == states.mach3 || obj_player2.state == states.climbwall || obj_player2.state == states.machslide || obj_player2.state == states.machroll || obj_player2.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 3, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player2.movespeed >= 9.6 && obj_player2.movespeed < 12 && (obj_player2.state == states.mach1 || obj_player2.state == states.mach2 || obj_player2.state == states.mach3 || obj_player2.state == states.climbwall || obj_player2.state == states.machslide || obj_player2.state == states.machroll || obj_player2.state == states.handstandjump))
            draw_sprite_ext(spr_speedbar, 4, 125, 140, 1, 1, 1, c_white, alpha)
        else if (obj_player2.movespeed >= 12 && (obj_player2.state == states.mach1 || obj_player2.state == states.mach2 || obj_player2.state == states.mach3 || obj_player2.state == states.climbwall || obj_player2.state == states.machslide || obj_player2.state == states.machroll || obj_player2.state == states.handstandjump))
            draw_sprite_ext(spr_speedbarmax, -1, 125, 140, 1, 1, 1, c_white, alpha)
    }
    with (obj_player1)
    {
        if (obj_player1.spotlight == 1 && character == "N")
        {
            with (other.id)
            {
                if (obj_player1.pogospeed < 10)
                    draw_sprite_ext(spr_speedbar, 0, 125, 140, 1, 1, 1, c_white, alpha)
                else if (obj_player1.pogospeed >= 10 && obj_player1.pogospeed < 14)
                    draw_sprite_ext(spr_speedbar, 3, 125, 140, 1, 1, 1, c_white, alpha)
                else if (obj_player1.pogospeed >= 14)
                    draw_sprite_ext(spr_speedbarmax, -1, 125, 140, 1, 1, 1, c_white, alpha)
            }
        }
    }
    with (obj_player2)
    {
        if (obj_player1.spotlight == 0 && character == "N")
        {
            with (other.id)
            {
                if (obj_player2.pogospeed < 10)
                    draw_sprite_ext(spr_speedbar, 0, 125, 140, 1, 1, 1, c_white, alpha)
                else if (obj_player2.pogospeed >= 10 && obj_player1.pogospeed < 14)
                    draw_sprite_ext(spr_speedbar, 3, 125, 140, 1, 1, 1, c_white, alpha)
                else if (obj_player2.pogospeed >= 14)
                    draw_sprite_ext(spr_speedbarmax, -1, 125, 140, 1, 1, 1, c_white, alpha)
            }
        }
    }
    if (obj_player.y < 200 && obj_player.x < 200)
        alpha = 0.5
    else
        alpha = 1
    font = font_add_sprite_ext(spr_font, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:", 1, 0)
    draw_set_font(font)
    draw_set_halign(fa_center)
    draw_set_color(c_white)
    if (global.panic == 1 || global.snickchallenge == 1 || global.miniboss == 1)
    {
        if (global.seconds < 10)
        {
            if (global.minutes < 1)
                draw_set_color(c_red)
            else
                draw_set_color(c_white)
            draw_text((random_range(1, -1) + 480), (random_range(1, -1) + 65), string_hash_to_newline(((string(global.minutes) + ":0") + string(global.seconds))))
        }
        else if (global.seconds >= 10)
        {
            if (global.minutes == 0 && global.seconds <= 30)
                draw_set_color(c_red)
            else
                draw_set_color(c_white)
            draw_text((random_range(1, -1) + 480), (random_range(1, -1) + 65), string_hash_to_newline(((string(global.minutes) + ":") + string(global.seconds))))
        }
    }
    if (global.key_inv == 1)
        draw_sprite_ext(spr_key, -1, 50, 30, 1, 1, 1, c_white, alpha)
    draw_sprite_ext(spr_inv, -1, 50, 30, 1, 1, 1, c_white, alpha)
}
draw_set_blend_mode(bm_normal)
