function live_preinit()
{
	global.g_gml_token_names = ["header", "macro", "hash", "semico", "comma", "period", "colon", "qmark", "at_sign", "keyword", "ident", "env", "undefined", "number", "cstring", "un_op", "in", "adjfix", "bin_op", "set_op", "par_open", "par_close", "sqb_open", "sqb_close", "cub_open", "cub_close", "arg_const", "comment_post", "comment_line", "comment_block"]
	global.g_gml_node_names = ["undefined", "number", "cstring", "enum_ctr", "array_decl", "object_decl", "ensure_array", "ident", "self", "other", "global_ref", "script", "native_script", "const", "arg_const", "arg_index", "arg_count", "call", "call_script", "call_script_at", "call_script_id", "call_field", "call_func", "call_func_at", "prefix", "postfix", "un_op", "bin_op", "set_op", "to_bool", "from_bool", "in", "local", "local_set", "local_aop", "global", "global_set", "global_aop", "field", "field_set", "field_aop", "env", "env_set", "env_aop", "env_fd", "env_fd_set", "env_fd_aop", "env1d", "env1d_set", "env1d_aop", "alarm", "alarm_set", "alarm_aop", "index", "index_set", "index_aop", "index_prefix", "index_postfix", "index2d", "index2d_set", "index2d_aop", "index2d_prefix", "index2d_postfix", "raw_id", "raw_id_set", "raw_id_aop", "raw_id_prefix", "raw_id_postfix", "raw_id2d", "raw_id2d_set", "raw_id2d_aop", "raw_id2d_prefix", "raw_id2d_postfix", "ds_list", "ds_list_set", "ds_list_aop", "ds_list_prefix", "ds_list_postfix", "ds_map", "ds_map_set", "ds_map_aop", "ds_map_prefix", "ds_map_postfix", "ds_grid", "ds_grid_set", "ds_grid_aop", "ds_grid_prefix", "ds_grid_postfix", "var_decl", "block", "if_then", "ternary", "switch", "wait", "fork", "while", "do_until", "do_while", "repeat", "for", "with", "once", "return", "exit", "break", "continue", "debugger", "comment_line", "comment_line_pre", "comment_line_post", "comment_line_sep", "comment_block", "comment_block_pre", "comment_block_post"]
	global.g_gml_action_names = ["discard", "dup", "dup2x", "dup_in", "undefined", "number", "cstring", "array_decl", "object_decl", "const", "self", "other", "local", "local_set", "local_aop", "global", "global_set", "global_aop", "field", "field_set", "field_aop", "index", "index_set", "index_aop", "index2d", "index2d_set", "index2d_aop", "env", "env_set", "env_aop", "env1d", "env1d_set", "env1d_aop", "ds_aop", "arg_const", "arg_const_set", "arg_const_aop", "arg_index", "arg_index_set", "arg_index_aop", "arg_count", "add_int", "equ_op", "neq_op", "add_op", "concat", "bin_op", "un_op", "in", "call_script", "call_script_id", "call_script_at", "call_func", "jump", "jump_if", "jump_unless", "bool_and", "bool_or", "switch", "repeat_jump", "repeat_pre", "with_pre", "with_next", "with_post", "break", "continue", "return", "result", "wait", "fork", "ensure_array_local", "ensure_array_global", "ensure_array_field", "alarm", "alarm_set", "alarm_aop"]
	global.mq_gml_builder = [undefined, undefined, undefined, 0, 0, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
	global.mq_gml_program = [undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
	global.mq_gml_enum = [undefined, undefined, undefined, undefined, undefined]
	global.mq_gml_enum_ctr = [undefined, undefined, undefined, undefined, 0]
	global.mq_gml_pos = [undefined, undefined, 0, 0]
	global.mq_gml_script = [undefined, undefined, undefined, 0, undefined, undefined, undefined, 0, 0, undefined, undefined]
	global.mq_gml_source = [undefined, undefined, undefined, undefined, 0, undefined, undefined, undefined]
	global.mq_gml_std_haxe_class = [undefined, undefined, 0, undefined, undefined]
	global.mq_gml_func_scope = [undefined, undefined, 0, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
	global.mq_gml_with_scope = [undefined, 0, 0, undefined, undefined, undefined]
	global.f_gml_seek_arguments_proc = asset_get_index("gml_seek_arguments_proc")
	global.f_gml_seek_locals_proc = asset_get_index("gml_seek_locals_proc")
	global.f_gml_seek_idents_proc = asset_get_index("gml_seek_idents_proc")
	global.f_gml_seek_fields_proc = asset_get_index("gml_seek_fields_proc")
	global.f_gml_seek_calls_proc = asset_get_index("gml_seek_calls_proc")
	global.f_gml_seek_enum_fields_proc = asset_get_index("gml_seek_enum_fields_proc")
	global.f_gml_seek_self_fields_proc = asset_get_index("gml_seek_self_fields_proc")
	global.f_gml_seek_alarms_proc = asset_get_index("gml_seek_alarms_proc")
	global.f_gml_seek_adjfix_proc = asset_get_index("gml_seek_adjfix_proc")
	global.f_gml_seek_set_op_proc = asset_get_index("gml_seek_set_op_proc")
	global.f_gml_type_check_any = asset_get_index("gml_type_check_any")
	global.f_gml_seek_eval_proc = asset_get_index("gml_seek_eval_proc")
	global.f_gml_seek_set_op_resolve_set_op_rfn = asset_get_index("gml_seek_set_op_resolve_set_op_rfn")
	global.f_live_log_impl = asset_get_index("live_log_impl")
	global.f_live_update_script_impl = asset_get_index("live_update_script_impl")
	global.f_live_room_updated_impl = asset_get_index("live_room_updated_impl")
	global.f_live_preinit_project_fake_call = asset_get_index("live_preinit_project_fake_call")
	global.f_live_execute_string = asset_get_index("live_execute_string")
	global.f_sprite_set_live = asset_get_index("sprite_set_live")
	global.f_room_goto_live = asset_get_index("room_goto_live")
	global.f_vm_gml_thread_exec_slice_with0 = asset_get_index("vm_gml_thread_exec_slice_with0")
	global.f_vm_gml_thread_exec_slice_with1 = asset_get_index("vm_gml_thread_exec_slice_with1")
	global.f_vm_gml_thread_exec_slice_with2 = asset_get_index("vm_gml_thread_exec_slice_with2")
	global.f_vm_gml_thread_exec_slice_with3 = asset_get_index("vm_gml_thread_exec_slice_with3")
	global.f_vm_gml_thread_exec_slice_with4 = asset_get_index("vm_gml_thread_exec_slice_with4")
	global.f_vm_gml_thread_exec_slice_with5 = asset_get_index("vm_gml_thread_exec_slice_with5")
	global.f_vm_gml_thread_exec_slice_with6 = asset_get_index("vm_gml_thread_exec_slice_with6")
	global.f_vm_gml_thread_exec_slice_with7 = asset_get_index("vm_gml_thread_exec_slice_with7")
	global.f_vm_gml_thread_exec_slice_with8 = asset_get_index("vm_gml_thread_exec_slice_with8")
	global.f_vm_gml_thread_exec_slice_with9 = asset_get_index("vm_gml_thread_exec_slice_with9")
	global.f_vm_gml_thread_exec_slice_with10 = asset_get_index("vm_gml_thread_exec_slice_with10")
	global.f_vm_gml_thread_exec_slice_with11 = asset_get_index("vm_gml_thread_exec_slice_with11")
	global.f_vm_gml_thread_exec_slice_with12 = asset_get_index("vm_gml_thread_exec_slice_with12")
	global.f_vm_gml_thread_exec_slice_with13 = asset_get_index("vm_gml_thread_exec_slice_with13")
	global.f_vm_gml_thread_exec_slice_with14 = asset_get_index("vm_gml_thread_exec_slice_with14")
	global.f_vm_gml_thread_exec_slice_with15 = asset_get_index("vm_gml_thread_exec_slice_with15")
	global.f_vm_gml_thread_exec_slice_with16 = asset_get_index("vm_gml_thread_exec_slice_with16")
	global.f_vm_gml_thread_exec_slice_with17 = asset_get_index("vm_gml_thread_exec_slice_with17")
	global.f_vm_gml_thread_exec_slice_with18 = asset_get_index("vm_gml_thread_exec_slice_with18")
	global.f_vm_gml_thread_exec_slice_with19 = asset_get_index("vm_gml_thread_exec_slice_with19")
	global.f_vm_gml_thread_exec_slice_with20 = asset_get_index("vm_gml_thread_exec_slice_with20")
	global.f_vm_gml_thread_exec_slice_with21 = asset_get_index("vm_gml_thread_exec_slice_with21")
	global.f_vm_gml_thread_exec_slice_with22 = asset_get_index("vm_gml_thread_exec_slice_with22")
	global.f_vm_gml_thread_exec_slice_with23 = asset_get_index("vm_gml_thread_exec_slice_with23")
	global.f_vm_gml_thread_exec_slice_with24 = asset_get_index("vm_gml_thread_exec_slice_with24")
	global.f_vm_gml_thread_exec_slice_with25 = asset_get_index("vm_gml_thread_exec_slice_with25")
	global.f_vm_gml_thread_exec_slice_with26 = asset_get_index("vm_gml_thread_exec_slice_with26")
	global.f_vm_gml_thread_exec_slice_with27 = asset_get_index("vm_gml_thread_exec_slice_with27")
	global.f_vm_gml_thread_exec_slice_with28 = asset_get_index("vm_gml_thread_exec_slice_with28")
	global.f_vm_gml_thread_exec_slice_with29 = asset_get_index("vm_gml_thread_exec_slice_with29")
	global.f_vm_gml_thread_exec_slice_with30 = asset_get_index("vm_gml_thread_exec_slice_with30")
	global.f_vm_gml_thread_exec_slice_with31 = asset_get_index("vm_gml_thread_exec_slice_with31")
	global.f_vm_gml_thread_exec_slice_with32 = asset_get_index("vm_gml_thread_exec_slice_with32")
	global.f_vm_gml_thread_exec_slice_with33 = asset_get_index("vm_gml_thread_exec_slice_with33")
	global.f_vm_gml_thread_exec_slice_with34 = asset_get_index("vm_gml_thread_exec_slice_with34")
	global.f_vm_gml_thread_exec_slice_with35 = asset_get_index("vm_gml_thread_exec_slice_with35")
	global.f_vm_gml_thread_exec_slice_with36 = asset_get_index("vm_gml_thread_exec_slice_with36")
	global.f_vm_gml_thread_exec_slice_with37 = asset_get_index("vm_gml_thread_exec_slice_with37")
	global.f_vm_gml_thread_exec_slice_with38 = asset_get_index("vm_gml_thread_exec_slice_with38")
	global.f_vm_gml_thread_exec_slice_with39 = asset_get_index("vm_gml_thread_exec_slice_with39")
	global.f_vm_gml_thread_exec_slice_with40 = asset_get_index("vm_gml_thread_exec_slice_with40")
	global.f_vm_gml_thread_exec_slice_with41 = asset_get_index("vm_gml_thread_exec_slice_with41")
	global.f_vm_gml_thread_exec_slice_with42 = asset_get_index("vm_gml_thread_exec_slice_with42")
	global.f_vm_gml_thread_exec_slice_with43 = asset_get_index("vm_gml_thread_exec_slice_with43")
	global.f_vm_gml_thread_exec_slice_with44 = asset_get_index("vm_gml_thread_exec_slice_with44")
	global.f_vm_gml_thread_exec_slice_with45 = asset_get_index("vm_gml_thread_exec_slice_with45")
	global.f_vm_gml_thread_exec_slice_with46 = asset_get_index("vm_gml_thread_exec_slice_with46")
	global.f_vm_gml_thread_exec_slice_with47 = asset_get_index("vm_gml_thread_exec_slice_with47")
	global.f_vm_gml_thread_exec_slice_with48 = asset_get_index("vm_gml_thread_exec_slice_with48")
	global.f_vm_gml_thread_exec_slice_with49 = asset_get_index("vm_gml_thread_exec_slice_with49")
	global.f_vm_gml_thread_exec_slice_with50 = asset_get_index("vm_gml_thread_exec_slice_with50")
	global.f_vm_gml_thread_exec_slice_with51 = asset_get_index("vm_gml_thread_exec_slice_with51")
	global.f_vm_gml_thread_exec_slice_with52 = asset_get_index("vm_gml_thread_exec_slice_with52")
	global.f_vm_gml_thread_exec_slice_with53 = asset_get_index("vm_gml_thread_exec_slice_with53")
	global.f_vm_gml_thread_exec_slice_with54 = asset_get_index("vm_gml_thread_exec_slice_with54")
	global.f_vm_gml_thread_exec_slice_with55 = asset_get_index("vm_gml_thread_exec_slice_with55")
	global.f_vm_gml_thread_exec_slice_with56 = asset_get_index("vm_gml_thread_exec_slice_with56")
	global.f_vm_gml_thread_exec_slice_with57 = asset_get_index("vm_gml_thread_exec_slice_with57")
	global.f_vm_gml_thread_exec_slice_with58 = asset_get_index("vm_gml_thread_exec_slice_with58")
	global.f_vm_gml_thread_exec_slice_with59 = asset_get_index("vm_gml_thread_exec_slice_with59")
	global.f_vm_gml_thread_exec_slice_with60 = asset_get_index("vm_gml_thread_exec_slice_with60")
	global.f_vm_gml_thread_exec_slice_with61 = asset_get_index("vm_gml_thread_exec_slice_with61")
	global.f_vm_gml_thread_exec_slice_with62 = asset_get_index("vm_gml_thread_exec_slice_with62")
	global.f_vm_gml_thread_exec_slice_with63 = asset_get_index("vm_gml_thread_exec_slice_with63")
	global.f_vm_gml_thread_exec_slice_with64 = asset_get_index("vm_gml_thread_exec_slice_with64")
	global.f_vm_gml_thread_exec_slice_with65 = asset_get_index("vm_gml_thread_exec_slice_with65")
	global.f_vm_gml_thread_exec_slice_with66 = asset_get_index("vm_gml_thread_exec_slice_with66")
	global.f_vm_gml_thread_exec_slice_with67 = asset_get_index("vm_gml_thread_exec_slice_with67")
	global.f_vm_gml_thread_exec_slice_with68 = asset_get_index("vm_gml_thread_exec_slice_with68")
	global.f_vm_gml_thread_exec_slice_with69 = asset_get_index("vm_gml_thread_exec_slice_with69")
	global.f_vm_gml_thread_exec_slice_with70 = asset_get_index("vm_gml_thread_exec_slice_with70")
	global.f_vm_gml_thread_exec_slice_with71 = asset_get_index("vm_gml_thread_exec_slice_with71")
	global.f_vm_gml_thread_exec_slice_with72 = asset_get_index("vm_gml_thread_exec_slice_with72")
	global.f_vm_gml_thread_exec_slice_with73 = asset_get_index("vm_gml_thread_exec_slice_with73")
	global.f_vm_gml_thread_exec_slice_with74 = asset_get_index("vm_gml_thread_exec_slice_with74")
	global.f_vm_gml_thread_exec_slice_with75 = asset_get_index("vm_gml_thread_exec_slice_with75")
	global.f_vm_gml_thread_exec_slice_with76 = asset_get_index("vm_gml_thread_exec_slice_with76")
	global.f_vm_gml_thread_exec_slice_with77 = asset_get_index("vm_gml_thread_exec_slice_with77")
	global.f_vm_gml_thread_exec_slice_with78 = asset_get_index("vm_gml_thread_exec_slice_with78")
	global.f_vm_gml_thread_exec_slice_with79 = asset_get_index("vm_gml_thread_exec_slice_with79")
	global.f_vm_gml_thread_exec_slice_with80 = asset_get_index("vm_gml_thread_exec_slice_with80")
	global.f_gml_type_check_number = asset_get_index("gml_type_check_number")
	global.f_gml_type_check_z_number = asset_get_index("gml_type_check_z_number")
	global.f_gml_type_check_int = asset_get_index("gml_type_check_int")
	global.f_gml_type_check_index = asset_get_index("gml_type_check_index")
	global.f_gml_type_check_string = asset_get_index("gml_type_check_string")
	global.f_gml_type_check_z_string = asset_get_index("gml_type_check_z_string")
	global.f_gml_type_check_array = asset_get_index("gml_type_check_array")
	global.f_gml_type_check_z_array = asset_get_index("gml_type_check_z_array")
	global.f_gml_program_callback = asset_get_index("gml_program_callback")
	global.f_gml_thread_callback = asset_get_index("gml_thread_callback")
	global.gml_std_haxe_type_markerValue = []
	global.mt_gml_builder = gml_std_haxe_class_create(7, "gml_builder")
	global.mt_gml_program = gml_std_haxe_class_create(8, "gml_program")
	global.mt_gml_enum = gml_std_haxe_class_create(9, "gml_enum")
	global.mt_gml_enum_ctr = gml_std_haxe_class_create(10, "gml_enum_ctr")
	global.mt_gml_pos = gml_std_haxe_class_create(11, "gml_pos")
	global.mt_gml_script = gml_std_haxe_class_create(12, "gml_script")
	global.mt_gml_source = gml_std_haxe_class_create(13, "gml_source")
	global.mt_gml_std_haxe_class = gml_std_haxe_class_create(15, "gml_std_haxe_class")
	global.mt_gml_func_scope = gml_std_haxe_class_create(17, "gml_func_scope")
	global.mt_gml_with_scope = gml_std_haxe_class_create(18, "gml_with_scope")
	global.g_gml_compile_curr_break = -1
	global.g_gml_compile_curr_continue = -1
	global.g_gml_parser_src_buf = buffer_create(1024, buffer_fast, 1)
	global.g_gml_parser_str_buf = buffer_create(1024, buffer_grow, 1)
	global.g_gml_parser_buf_sub_buf = buffer_create(1024, buffer_grow, 1)
	global.g_gml_std_mathnf_not_a_number = gml_std_mathnf_init(0, 0)
	global.g_gml_sig_list = ds_list_create()
	global.g_gml_func_sig = ds_map_create()
	global.g_gml_func_arg0 = ds_map_create()
	global.g_gml_func_arg1 = ds_map_create()
	global.g_gml_func_args = ds_map_create()
	global.g_gml_func_rest = ds_map_create()
	global.g_gml_func_eval = ds_map_create()
	global.g_gml_func_script = ds_map_create()
	global.g_gml_func_script_id = ds_map_create()
	global.g_gml_inst_data = ds_map_create()
	global.g_gml_scope_separator = ""
	global.g_gml_scope_lookup = ds_map_create()
	global.g_gml_scope_fields = ds_map_create()
	var l_defscope = ds_map_create()
	ds_map_set(global.g_gml_scope_lookup, "", l_defscope)
	ds_map_set(global.g_gml_scope_fields, l_defscope, "")
	global.g_gml_scope_default = l_defscope
	global.g_gml_scope_list = ds_list_create()
	global.g_gml_var_flags = ds_map_create()
	global.g_gml_var_refs = ds_map_create()
	global.g_gml_var_types = ds_map_create()
	global.g_gml_pf_readonly = 1
	global.g_gml_pf_array = 2
	global.g_gml_pf_inst = 4
	global.g_gml_const_map = ds_map_create()
	global.g_gml_const_val = ds_map_create()
	global.g_gml_asset_kind = ds_map_create()
	global.g_gml_asset_index = ds_map_create()
	global.g_gml_seek_eval_eval_thread = undefined
	global.g_gml_seek_eval_eval_actions = ds_list_create()
	global.g_gml_seek_eval_invalid_value = []
	global.g_live_is_ready = 0
	global.g_live_request_url = undefined
	global.g_live_request_guid = undefined
	global.g_live_request_id = undefined
	global.g_live_request_time = 0
	global.g_live_request_rate = 1
	global.g_live_request_password = ""
	global.g_live_result = ""
	global.g_live_live_map = ds_map_create()
	global.g_live_live_list = ds_list_create()
	global.g_live_live_enums = ds_map_create()
	global.g_live_live_macros = ds_map_create()
	global.g_live_live_globals = undefined
	global.g_live_live_sprites = ds_map_create()
	global.g_live_live_sprites_start = ds_list_create()
	global.g_live_live_sprites_stop = ds_list_create()
	global.g_live_live_room = -1
	global.g_live_live_room_data = ds_map_create()
	global.g_live_live_rooms = ds_map_create()
	global.g_live_live_rooms_start = ds_list_create()
	global.g_live_live_rooms_stop = ds_list_create()
	global.g_live_blank_object = -1
	global.g_live_blank_room = -1
	global.g_live_temp_path = ("gmlive-" + string(date_current_datetime()))
	global.g_live_bug24929_map = live_bug24929_init()
	global.g_live_log_script = global.f_live_log_impl
	global.g_live_update_script = global.f_live_update_script_impl
	global.g_live_room_updated = global.f_live_room_updated_impl
	global.g_live_async_http_1_found = ds_map_create()
	global.g_live_async_http_1_acc = ds_list_create()
	global.g_live_room_loader_object_cache = ds_map_create()
	global.g_live_room_loader_sprite_cache = ds_map_create()
	global.g_live_room_loader_use_physics = 0
	global.g_live_room_loader_room_x = 0
	global.g_live_room_loader_room_y = 0
	global.g_live_room_loader_apply_backgrounds = 1
	global.g_live_room_loader_apply_instances = 1
	global.g_live_room_loader_apply_tiles = 1
	global.g_live_room_loader_apply_views = 1
	global.g_live_room_loader_apply_settings = 1
	global.g_live_room_loader_apply_sprites = 1
	global.g_live_room_loader_inst_map_gml = ds_map_create()
	global.g_live_room_loader_inst_map_yy = ds_map_create()
	global.g_gml_object_fields = gml_object_init()
	global.g_gml_thread_current = undefined
	global.g_vm_gml_thread_exec_slice_funcs = vm_gml_thread_exec_slice_init()
	global.g_gml_type_check_map = gml_type_check_init()
	global.g_gml_value_print_refs = ds_map_create()
	global.g_gml_value_print_num = 0
	global.g_vm__gml_with_data_gml_with_data_impl__pools = vm__gml_with_data_gml_with_data_impl__init()
	live_preinit_api()
	live_preinit_project()
}
