var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1279)
    layer_background_sprite(back_id, 1278)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1276)
    layer_background_sprite(back_id, 1277)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 1281)
    layer_background_sprite(back_id3, 1282)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1245)
    layer_background_sprite(back_id, 1246)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1248)
    layer_background_sprite(back_id, 1249)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 1250)
    layer_background_sprite(back_id2, 1251)
if (global.panic == 1 && layer_background_get_sprite(back_id) == 1317)
    layer_background_sprite(back_id, 1318)
if (global.panic == 1 && layer_background_get_sprite(back_id2) == 1315)
    layer_background_sprite(back_id2, 1316)
if (global.panic == 1 && layer_background_get_sprite(back_id3) == 1313)
    layer_background_sprite(back_id3, 1314)
