function __lnc_const_decl_f19()
{
	gml_const_add("kbv_returnkey_go", 1)
	gml_const_add("kbv_returnkey_google", 2)
	gml_const_add("kbv_returnkey_join", 3)
	gml_const_add("kbv_returnkey_next", 4)
	gml_const_add("kbv_returnkey_route", 5)
	gml_const_add("kbv_returnkey_search", 6)
	gml_const_add("kbv_returnkey_send", 7)
	gml_const_add("kbv_returnkey_yahoo", 8)
	gml_const_add("kbv_returnkey_done", 9)
	gml_const_add("kbv_returnkey_continue", 10)
	gml_const_add("kbv_returnkey_emergency", 11)
	gml_const_add("kbv_autocapitalize_none", 0)
	gml_const_add("kbv_autocapitalize_words", 1)
	gml_const_add("kbv_autocapitalize_sentences", 2)
	gml_const_add("kbv_autocapitalize_characters", 3)
	gml_const_add("os_permission_denied_dont_request", -1)
	gml_const_add("os_permission_denied", 0)
	gml_const_add("os_permission_granted", 1)
}
