thrown = 0
grabbed = 0
hsp = 0
vsp = 0
grav = 0.5
flash = 1
hp = 0
grounded = 1
state = states.normal
playerid = 3
image_speed = 0
image_index = random_range(0, (image_number - 1))
mask_index = spr_player_mask
depth = -5
